config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  	confirmations: 'users/confirmations',
  	passwords: 'users/passwords',
  	registrations: 'users/registrations',
  	sessions: 'users/sessions',
  	unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :products
  get '/products', to: 'products#index', as: :products
  get '/product/:id', to: 'products#show', as: :product
  get '/dashboard/products', to: 'products#manage_products', as: :manage_products
  get '/dashboard/products/new', to: 'products#new', as: :new_product
  post '/dashboard/products', to: 'products#create', as: :create_product
  get '/dashboard/product/:id/edit', to: 'products#edit', as: :edit_product
  put '/dashboard/product/:id', to: 'products#update', as: :update_product
  delete '/dashboard/product/:id', to: 'products#destroy', as: :delete_product

  resource :user do
    resources :shipping_addresses
  end

  resource :cart
  post 'cart_items' => 'carts#batch_process', as: :cart_item_batch_process

  get 'order/:id/shipping-address' => 'orders#fill_shipping_address', as: :fill_order_shipping_address
  post 'order/:id/shipping-address' => 'orders#save_shipping_address', as: :save_order_shipping_address
  get 'orders' => 'orders#index', as: :orders
  get '/dashboard/orders' => 'orders#manage_orders', as: :manage_orders
  match '/dashboard/order/:id/update_status' => 'orders#update_status', via: [:get, :put], as: :update_order_status

  root to: "products#index"
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items

  # enum status: {
  # 	draft: 0,
  # 	paid: 1,
  # 	pending: 2,
  # 	confirmed: 3,
  # 	shipped: 4,
  # 	fulfilled: 5,
  # 	canceled: 6,
  # 	completed: 7
  # }
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!

  def index
  	@orders = Order.where(user: current_user)
  end

  def manage_orders
  	@orders = Order.all
  	render 'admin_index'
  end

  def fill_shipping_address
  	@order = Order.find_by(id: params[:id], user: current_user)
  	if @order.nil? or @order.shipping_address.nil?
  	  @shipping_address = {}
  	else
  	  @shipping_address = JSON.parse @order.shipping_address
  	end
  end

  def save_shipping_address
  	shipping_address = params.require(:shipping_address).permit(:name, :address1, :address2, :city, :state, :country, :phone)

  	order = Order.find_by(id: params[:id], user: current_user)
  	unless order.nil?
  	  if order.status == 'draft'
  	    order.update(shipping_address: shipping_address.to_json, status: 'pending')
  	  else
  	    order.update(shipping_address: shipping_address.to_json)
  	  end
  	end

  	redirect_to orders_url
  end

  def update_status
	@order = Order.find_by(id: params[:id])
	if @order.nil?
	  redirect_to manage_orders_url
	  return
	end

  	if request.get?
	  @statuses = [['Draft', 'draft'], ['Paid', 'paid'], ['Pending', 'Pending'], ['Confirmed', 'confirmed'], ['Shipped', 'shipped'], ['Fulfilled', 'fulfilled'], ['Completed', 'completed'], ['Cancelled', 'cancelled']]
	  render 'update_status'
	else
	  @order.update(status: params[:status])
	  redirect_to manage_orders_url
	end
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form_shipping_address.html.erb
<div class="row">
  <%= form_tag(save_order_shipping_address_url, method: :post) do %>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= label_tag :name, nil, class: 'control-label' %>
      <%= text_field_tag 'shipping_address[name]', @shipping_address.fetch('name', nil), class: 'form-control', placeholder: 'Enter Name Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= label_tag :address1, nil, class: 'control-label' %>
      <%= text_field_tag 'shipping_address[address1]', @shipping_address.fetch('address1', nil), class: 'form-control', placeholder: 'Enter address1 Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= label_tag :address2, nil, class: 'control-label' %>
      <%= text_field_tag 'shipping_address[address2]', @shipping_address.fetch('address2', nil), class: 'form-control', placeholder: 'Enter address2 Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= label_tag :city, nil, class: 'control-label' %>
      <%= text_field_tag 'shipping_address[city]', @shipping_address.fetch('city', nil), class: 'form-control', placeholder: 'Enter city Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= label_tag :state, nil, class: 'control-label' %>
      <%= text_field_tag 'shipping_address[state]', @shipping_address.fetch('state', nil), class: 'form-control', placeholder: 'Enter state Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= label_tag :country, nil, class: 'control-label' %>
      <%= text_field_tag 'shipping_address[country]', @shipping_address.fetch('country', nil), class: 'form-control', placeholder: 'Enter country Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= label_tag :phone, nil, class: 'control-label' %>
      <%= text_field_tag 'shipping_address[phone]', @shipping_address.fetch('phone', nil), class: 'form-control', placeholder: 'Enter phone Here' %>
    </div>
  </div>

  <%= submit_tag 'Save', class: "btn btn-sm btn-primary" %>
  <% end %>
</div>

app/views/orders/admin_index.html.erb
<div class="page-header">
  <h1>Your Orders</h1>
</div>

<div class="row">
  <div class="col-xs-12 table-responsive">
    <table class="table table-hover">
      <thead>
      	<tr>
      	  <th>ID</th>
      	  <th>Items</th>
      	  <th>Shipping Address</th>
      	  <th>Total</th>
      	  <th>Stauts</th>
      	  <th>Action</th>
      	</tr>
      </thead>
      <tbody>
      	<% @orders.each do |order| %>
      	<tr>
      	  <td><%= order.id %></td>
      	  <td>
      	  	<ul class="media-list">
	      	<% order.order_items.each do |order_item| %>
      	  	  <li class="media">
		        <% unless order_item.image.nil? %>
		        <div class="media-left media-middle">
		      	  <img class="media-object" src="<%= order_item.image %>" />
		        </div>
		        <% end %>
		        <div class="media-body">
		      	  <h4 class="media-heading"><%= order_item.title %></h4>
		          <p class="text-danger">Price: <%= order_item.price %></p>
		      	  <p class="text-danger">Quantity: <%= order_item.quantity %></p>
		        </div>
	          </li>
	      	<% end %>
	        </ul>
      	  </td>
      	  <td>
      	  	<% unless order.shipping_address.nil? %>
      	  	<% addr = JSON.parse order.shipping_address %>
      	  	<ul class="list-group">
      	  	<% addr.each_pair do |key, value| %>
      	  	  <li class="list-group-item"><%= key %>: <%= value %></li>
      	  	<% end %>
      	  	</ul>
      	  	<% end %>
      	  </td>
      	  <td><%= order.total %></td>
      	  <td><%= order.status.capitalize %></td>
      	  <td><%= link_to 'Update Status', update_order_status_url(order), class: 'btn btn-primary' %></td>
      	</tr>
      	<% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/fill_shipping_address.html.erb
<div class="page-header">
  <h1>Fill Shipping Address</h1>
</div>

<section class="content">
  <%= render 'form_shipping_address' %>
</section>

app/views/orders/index.html.erb
<div class="page-header">
  <h1>Your Orders</h1>
</div>

<div class="row">
  <div class="col-xs-12 table-responsive">
    <table class="table table-hover">
      <thead>
      	<tr>
      	  <th>ID</th>
      	  <th>Items</th>
      	  <th>Shipping Address</th>
      	  <th>Total</th>
      	  <th>Stauts</th>
      	  <th>Action</th>
      	</tr>
      </thead>
      <tbody>
      	<% @orders.each do |order| %>
      	<tr>
      	  <td><%= order.id %></td>
      	  <td>
      	  	<ul class="media-list">
	      	<% order.order_items.each do |order_item| %>
      	  	  <li class="media">
		        <% unless order_item.image.nil? %>
		        <div class="media-left media-middle">
		      	  <img class="media-object" src="<%= order_item.image %>" />
		        </div>
		        <% end %>
		        <div class="media-body">
		      	  <h4 class="media-heading"><%= order_item.title %></h4>
		          <p class="text-danger">Price: <%= order_item.price %></p>
		      	  <p class="text-danger">Quantity: <%= order_item.quantity %></p>
		        </div>
	          </li>
	      	<% end %>
	        </ul>
      	  </td>
      	  <td>
      	  	<% unless order.shipping_address.nil? %>
      	  	<% addr = JSON.parse order.shipping_address %>
      	  	<ul class="list-group">
      	  	<% addr.each_pair do |key, value| %>
      	  	  <li class="list-group-item"><%= key %>: <%= value %></li>
      	  	<% end %>
      	  	</ul>
      	  	<% end %>
      	  </td>
      	  <td><%= order.total %></td>
      	  <td><%= order.status.capitalize %></td>
      	  <td><%= link_to 'Update Shipping', fill_order_shipping_address_url(order), class: 'btn btn-primary' %></td>
      	</tr>
      	<% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/orders/update_status.html.erb
<div class="page-header">
  <h1>Edit Order <%= @order.id %> Status</h1>
</div>

<section class="content">
  <div class="row">
    <%= form_tag(update_order_status_url, method: :put) do %>
    <div class="form-group">
      <div class="input-group input-group-sm">
        <%= label_tag :status, nil, class: 'control-label' %>
        <%= select_tag 'status', options_for_select(@statuses), class: 'form-control' %>
      </div>
    </div>
    <%= submit_tag 'Save', class: "btn btn-sm btn-primary" %>
    <% end %>
  </div>
</section>