config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  	confirmations: 'users/confirmations',
  	passwords: 'users/passwords',
  	registrations: 'users/registrations',
  	sessions: 'users/sessions',
  	unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :products
  get '/products', to: 'products#index', as: :products
  get '/product/:id', to: 'products#show', as: :product
  get '/dashboard/products', to: 'products#manage_products', as: :manage_products
  get '/dashboard/products/new', to: 'products#new', as: :new_product
  post '/dashboard/products', to: 'products#create', as: :create_product
  get '/dashboard/product/:id/edit', to: 'products#edit', as: :edit_product
  put '/dashboard/product/:id', to: 'products#update', as: :update_product
  delete '/dashboard/product/:id', to: 'products#destroy', as: :delete_product

  resource :user do
    resources :shipping_addresses
  end

  resource :cart
  post 'cart_items' => 'carts#batch_process', as: :cart_item_batch_process

  get 'order/:id/shipping-address' => 'orders#fill_shipping_address', as: :fill_order_shipping_address
  post 'order/:id/shipping-address' => 'orders#save_shipping_address', as: :save_order_shipping_address
  get 'orders' => 'orders#index', as: :orders
  get '/dashboard/orders' => 'orders#manage_orders', as: :manage_orders
  match '/dashboard/order/:id/update_status' => 'orders#update_status', via: [:get, :put], as: :update_order_status

  root to: "products#index"
end

app/controllers/shipping_addresses_controller.rb
class ShippingAddressesController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!

  def index
    @shipping_addresses = ShippingAddress.where(user: current_user)
  end

  def new
    @shipping_address = ShippingAddress.new
  end

  def create
    default_addr = current_user.shipping_addresses.find {|addr| addr.default }

    @shipping_address = ShippingAddress.new(shipping_address_params)
    @shipping_address.user = current_user
    if @shipping_address.save
      if @shipping_address.default
        default_addr.update(default: false)
      end
      redirect_to user_shipping_addresses_url
    else
      render 'new'
    end
  end

  def edit
    @shipping_address = ShippingAddress.find_by(id: params[:id], user: current_user)
  end

  def update
    @shipping_address = ShippingAddress.find_by(id: params[:id])
    if @shipping_address.nil?
      redirect_to user_shipping_addresses_url
    else
      default_addr = current_user.shipping_addresses.find {|addr| addr.default }
      if @shipping_address.update(shipping_address_params)
        if shipping_address_params[:default]
          default_addr.update(default: false) unless default_addr.nil?
        end
      else
        render 'edit'
      end
    end
  end

  def destroy
    @shipping_address = ShippingAddress.find_by(id: params[:id], user: current_user)
    unless @shipping_address.nil?
      @shipping_address.destroy
    end
    redirect_to user_shipping_addresses_url
  end

  private
    def shipping_address_params
      params.require(:shipping_address).permit(:name, :address1, :address2, :city, :state, :country, :phone, :default)
    end
end

app/helpers/shipping_addresses_helper.rb
module ShippingAddressesHelper
end

app/views/shipping_addresses/_form.html.erb
<div class="row">
  <% if @shipping_address.id.nil? %>
  <% options = { method: :post, url: user_shipping_addresses_path } %>
  <% else %>
  <% options = { method: :put, url: user_shipping_address_path(@shipping_address) } %>
  <% end %>
  <% options[:html] = { class: 'shipping-address-form' } %>

  <%= form_for(@shipping_address, options) do |f| %>
  <% if @shipping_address.errors.any? %>
  <% @shipping_address.errors.full_messages.each do |msg| %>
  <p class="text-danger"><%= msg %></p>
  <% end %>
  <% end %>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= f.label :name, class: 'control-label' %>
      <%= f.text_field :name, class: 'form-control', placeholder: 'Enter Name Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= f.label :address1, class: 'control-label' %>
      <%= f.text_field :address1, class: 'form-control', placeholder: 'Enter address1 Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= f.label :address2, class: 'control-label' %>
      <%= f.text_field :address2, class: 'form-control', placeholder: 'Enter address2 Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= f.label :city, class: 'control-label' %>
      <%= f.text_field :city, class: 'form-control', placeholder: 'Enter city Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= f.label :state, class: 'control-label' %>
      <%= f.text_field :state, class: 'form-control', placeholder: 'Enter state Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= f.label :country, class: 'control-label' %>
      <%= f.text_field :country, class: 'form-control', placeholder: 'Enter country Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= f.label :phone, class: 'control-label' %>
      <%= f.text_field :phone, class: 'form-control', placeholder: 'Enter phone Here' %>
    </div>
  </div>
  <div class="form-group">
    <div class="input-group input-group-sm">
      <%= f.label :default do %>
      <%= f.check_box :default %> Default Address?
      <% end %>
    </div>
  </div>

  <%= f.submit 'Add', class: "btn btn-sm btn-primary" %>
  <% end %>
</div>

app/views/shipping_addresses/edit.html.erb
<div class="page-header">
  <h1>Edit Shipping Address</h1>
</div>

<section class="content">
  <%= render 'form' %>
</section>

app/views/shipping_addresses/index.html.erb
<div class="page-header">
  <h1>Your Shipping Addresses</h1>
  <p>
    <%= link_to 'Add Shipping Address', new_user_shipping_address_url %>
  </p>
</div>

<div class="row">
  <% if @shipping_addresses.nil? or @shipping_addresses.size <= 0 %>
  <p>You have no shipping address now!</p>
  <% else %>
  <table class="table">
    <thead>
      <tr>
        <th>Name</th>
        <th>Address1</th>
        <th>Address2</th>
        <th>City</th>
        <th>State</th>
        <th>Country</th>
        <th>Phone</th>
        <th>Default</th>
        <th>Action</th>
      </tr>
    </thead>
    <tbody>
      <% @shipping_addresses.each do |addr| %>
      <tr>
        <td><%= addr.name %></td>
        <td><%= addr.address1 %></td>
        <td><%= addr.address2 %></td>
        <td><%= addr.city %></td>
        <td><%= addr.state %></td>
        <td><%= addr.country %></td>
        <td><%= addr.phone %></td>
        <td><%= addr.default ? 'Yes' : 'No' %></td>
        <td>
          <%= link_to 'Edit', edit_user_shipping_address_url(addr), class: 'btn btn-xs btn-primary' %>
          <%= link_to 'Delete', user_shipping_address_url(addr), method: :delete, data: { confirm: "Do you really want to delete this address?" }, class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
  <% end %>
</div>

app/views/shipping_addresses/new.html.erb
<div class="page-header">
  <h1>Add Shipping Address</h1>
</div>

<section class="content">
  <%= render 'form' %>
</section>