config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  	confirmations: 'users/confirmations',
  	passwords: 'users/passwords',
  	registrations: 'users/registrations',
  	sessions: 'users/sessions',
  	unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :products
  get '/products', to: 'products#index', as: :products
  get '/product/:id', to: 'products#show', as: :product
  get '/dashboard/products', to: 'products#manage_products', as: :manage_products
  get '/dashboard/products/new', to: 'products#new', as: :new_product
  post '/dashboard/products', to: 'products#create', as: :create_product
  get '/dashboard/product/:id/edit', to: 'products#edit', as: :edit_product
  put '/dashboard/product/:id', to: 'products#update', as: :update_product
  delete '/dashboard/product/:id', to: 'products#destroy', as: :delete_product

  resource :user do
    resources :shipping_addresses
  end

  resource :cart
  post 'cart_items' => 'carts#batch_process', as: :cart_item_batch_process

  get 'order/:id/shipping-address' => 'orders#fill_shipping_address', as: :fill_order_shipping_address
  post 'order/:id/shipping-address' => 'orders#save_shipping_address', as: :save_order_shipping_address
  get 'orders' => 'orders#index', as: :orders
  get '/dashboard/orders' => 'orders#manage_orders', as: :manage_orders
  match '/dashboard/order/:id/update_status' => 'orders#update_status', via: [:get, :put], as: :update_order_status

  root to: "products#index"
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  mount_uploader :image, ProductImageUploader

  validates :title, presence: true
  validates :inventory, presence: true
  validates :price, presence: true
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  protect_from_forgery
  before_action :authenticate_user!, except: [:show, :index]
  before_action :is_seller?, except: [:show, :index]

  def index
  	@products = Product.all
  end

  def manage_products
    if user_signed_in? and current_user.seller?
      @products = Product.where(user: current_user)

      render 'admin_index'
    else
      redirect_to manage_products_url
    end
  end

  def show
    @product = Product.find_by(id: params[:id])
  end

  def new
  	@product = Product.new
  end

  def create
  	@product = Product.new(product_params)
  	@product.user = current_user
  	if @product.save
  	  redirect_to products_url
  	else
  	  render 'new'
  	end
  end

  def edit
  	@product = Product.find_or_create_by(id: params[:id], user: current_user)
  end

  def update
  	@product = Product.find_by(id: params[:id], user: current_user)
  	if @product.nil?
  	  redirect_to products_url
  	elsif @product.update(product_params)
  	  redirect_to products_url
  	else
  	  render 'edit'
  	end
  end

  def destroy
  	@product = Product.find_by(id: params[:id], user: current_user)
  	unless @product.nil?
  	  @product.destroy
  	end
  	redirect_to products_url
  end

  def is_seller?
    redirect_to root_url unless current_user.seller?
  end

  private
    def product_params
      params.require(:product).permit(:title, :description, :price, :inventory, :image, :image_cache, :remove_image)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<div class="row">
  <% if @product.id.nil? %>
  <% options = { method: :post, url: create_product_path } %>
  <% else %>
  <% options = { method: :put, url: update_product_path(@product) } %>
  <% end %>
  <% options[:html] = { class: 'product-form' } %>

  <%= form_for(@product, options) do |f| %>
  <% if @product.errors.any? %>
  <% @product.errors.full_messages.each do |msg| %>
  <p class="text-danger"><%= msg %></p>
  <% end %>
  <% end %>
  <div class="form-group">
  	<div class="input-group input-group-sm">
  	  <%= f.label :title, class: 'control-label' %>
  	  <%= f.text_field :title, class: 'form-control', placeholder: 'Enter Title Here' %>
  	</div>
  </div>
  <div class="form-group">
  	<div class="input-group input-group-sm">
  	  <%= f.label :description, class: 'control-label' %>
  	  <%= f.text_area :description, class: 'form-control', placeholder: 'Enter Description Here' %>
  	</div>
  </div>
  <div class="form-group">
  	<div class="input-group input-group-sm">
  	  <%= f.label :price, class: 'control-label' %>
  	  <%= f.number_field :price, in: 0.0..10000.0, step: 0.01, class: 'form-control', placeholder: 'Enter Price Here' %>
  	</div>
  </div>
  <div class="form-group">
  	<div class="input-group input-group-sm">
  	  <%= f.label :inventory, class: 'control-label' %>
  	  <%= f.number_field :inventory, class: 'form-control', placeholder: 'Enter Quantity Here' %>
  	</div>
  </div>
  <div class="form-group">
  	<div class="input-group input-group-sm">
  	  <%= f.label :image, class: 'control-label' %>
  	  <%= f.file_field :image, class: 'form-control' %>
  	</div>
  </div>
  <%= f.hidden_field :image_cache %>

  <%= f.submit 'Add', class: "btn btn-sm btn-primary" %>
  <% end %>
</div>

app/views/products/_product.html.erb
<li class="media">
  <% unless product.image.thumb.file.nil? %>
  <div class="media-left">
  	<a href="<%= product_url(product) %>">
  		<image class="media-object" src="<%= product.image.thumb.url %>" />
  	</a>
  </div>
  <% end %>
  <div class="media-body">
  	<h4 class="media-heading">
      <a href="<%= product_url(product) %>">
        <%= product.title %>
      </a>
    </h4>
  	<p><%= product.description %></p>
  </div>
</li>

app/views/products/admin_index.html.erb
<div class="panel panel-default">
  <div class="panel-heading">Catalog</div>
  <div class="panel-body">
  	<a href="<%= new_product_url %>" class="btn btn-primary">Add Product</a>
  </div>
  <table class="table">
  	<thead>
  	  <tr>
  	  	<th>ID</th>
  	  	<th>Image</th>
  	  	<th>Title</th>
  	  	<th>Price</th>
  	  	<th>Inventory</th>
  	  	<th>Action</th>
  	  </tr>
  	</thead>
  	<tbody>
  	  <% @products.each do |product| %>
  	  <tr>
  	  	<td><%= product.id %></td>
  	  	<% if product.image.file.nil? %>
  	  	<td></td>
  	  	<% else %>
  	  	<td>
  	  	  <img src="<%= product.image.thumb.url %>" />
  	  	</td>
  	  	<% end %>
  	  	<td><%= product.title %></td>
  	  	<td><%= product.price %></td>
  	  	<td><%= product.inventory %></td>
  	  	<td>
  	  	  <%= link_to 'Edit', edit_product_url(product), class: 'btn btn-xs btn-primary' %>
  	  	  <%= link_to 'Delete', delete_product_url(product), method: :delete, data: { confirm: "You cannot recover the meterial that has been deleted. \n\nDo you still want to delete?" }, class: 'btn btn-xs btn-danger' %>
  	  	</td>
  	  </tr>
  	  <% end %>
  	</tbody>
  </table>
</div>

app/views/products/edit.html.erb
<div class="page-header">
  <h1>Edit Product</h1>
</div>

<section class="content">
  <%= render 'form' %>
</section>

app/views/products/index.html.erb
<div class="page-header">
  <h1>Catalog</h1>
</div>

<div class="row">
  <% if @products.nil? or @products.size <= 0 %>
  <p>There is no product now!</p>
  <% else %>
  <ul class="media-list">
    <%= render partial: 'product', collection: @products %>
  </ul>
  <% end %>
</div>

app/views/products/new.html.erb
<div class="page-header">
  <h1>Add Product</h1>
</div>

<section class="content">
  <%= render 'form' %>
</section>

app/views/products/show.html.erb
<div class="row">
  <div class="panel panel-default">
  	<div class="panel-heading">
  		<h3 class="panel-title"><%= @product.title %></h3>
  	</div>
  	<div class="panel-body">
      <% if flash[:notice] %>
        <p class="text-warning"><%= flash[:notice] %></p>
      <% end %>

  	  <% unless @product.image.file.nil? %>
  	  <img src="<%= @product.image.url %>" />
  	  <% end %>
  	  <p>Price: <%= @product.price %></p>
  	  <p>Quantity: <%= @product.inventory %></p>
  	  <p><%= @product.description %></p>
      <%= form_tag(cart_url, method: :post) do %>
        <%= hidden_field_tag(:product_id, @product.id) %>
        <%= submit_tag 'Add To Cart', class: 'btn btn-primary' %>
      <% end %>
  	</div>
  </div>
</div>