config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
  	confirmations: 'users/confirmations',
  	passwords: 'users/passwords',
  	registrations: 'users/registrations',
  	sessions: 'users/sessions',
  	unlocks: 'users/unlocks'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  #resources :products
  get '/products', to: 'products#index', as: :products
  get '/product/:id', to: 'products#show', as: :product
  get '/dashboard/products', to: 'products#manage_products', as: :manage_products
  get '/dashboard/products/new', to: 'products#new', as: :new_product
  post '/dashboard/products', to: 'products#create', as: :create_product
  get '/dashboard/product/:id/edit', to: 'products#edit', as: :edit_product
  put '/dashboard/product/:id', to: 'products#update', as: :update_product
  delete '/dashboard/product/:id', to: 'products#destroy', as: :delete_product

  resource :user do
    resources :shipping_addresses
  end

  resource :cart
  post 'cart_items' => 'carts#batch_process', as: :cart_item_batch_process

  get 'order/:id/shipping-address' => 'orders#fill_shipping_address', as: :fill_order_shipping_address
  post 'order/:id/shipping-address' => 'orders#save_shipping_address', as: :save_order_shipping_address
  get 'orders' => 'orders#index', as: :orders
  get '/dashboard/orders' => 'orders#manage_orders', as: :manage_orders
  match '/dashboard/order/:id/update_status' => 'orders#update_status', via: [:get, :put], as: :update_order_status

  root to: "products#index"
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
  	<div class="collapse navbar-collapse" id="buyer-nav">
  	  <ul class="nav navbar-nav">
        <% if user_signed_in? and current_user.seller? %>
        <li>
          <a href="<%= manage_products_url %>">Products</a>
        </li>
        <li>
          <%= link_to 'Orders', manage_orders_url %>
        </li>
        <% else %>
        <li class="active">
          <a href="<%= products_url %>">Products</a>
        </li>
        <% end %>
  	  </ul>
  	  <ul class="nav navbar-nav navbar-right">
  	  	<% if user_signed_in? %>
  	  	<li class="dropdown">
  	  	  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
  	  	  	<%= current_user.name %> <span class="caret"></span>
  	  	  </a>
  	  	  <ul class="dropdown-menu">
            <li><%= link_to 'Cart', cart_url %></li>
            <li><%= link_to 'Shipping Addresses', user_shipping_addresses_url %></li>
            <li><%= link_to 'Orders', orders_url %></li>
  	  	  	<li><%= link_to 'Edit Profile', edit_user_registration_url %></li>
  	  	  	<li><%= link_to 'Logout', destroy_user_session_url, method: :delete %></li>
  	  	  </ul>
  	  	</li>
  	  	<% else %>
  	  	<li><a href="<%= new_user_session_url %>">Sign In</a></li>
  	  	<li><a href="<%= new_user_registration_url %>">Sign Up</a></li>
  	  	<% end %>
  	  </ul>
  	</div>
  </div>
</nav>

app/views/layouts/_selection.html.erb
<script type="text/javascript">
	var itemSelector = '.select-item';
	var allSelector = 'input[name="select-all"]';

	var imageSelection = new SimpleSelection({
		itemSelector: itemSelector,
		allSelector: allSelector
	});
	$(allSelector).change(function() {
		if ($(this).is(':checked')) {
			imageSelection.selectAll();
		} else {
			imageSelection.deselectAll();
		}
	});
</script>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ShoppingCart</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= render 'layouts/shim' %>
  </head>

  <body>
  	<%= render 'layouts/header' %>
  	<div class="container">
      <%= yield %>
  	</div>
    <%= render 'layouts/selection' %>
    <%= yield :script %>
  </body>
</html>